favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: 'public://cash_logo.png'
  use_default: false
third_party_settings:
  shortcut:
    module_link: true
