_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  auto_entitylabel: -100
  action: 0
  address: 0
  admin_toolbar: 0
  atom8: 0
  automated_cron: 0
  backup_migrate: 0
  barcodes: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  bpmn_io: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  coffee: 0
  comment: 0
  config: 0
  config_ignore: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_content: 0
  eca_endpoint: 0
  eca_log: 0
  eca_misc: 0
  eca_modeller_bpmn: 0
  eca_ui: 0
  eca_user: 0
  eca_views: 0
  eca_workflow: 0
  editablefields: 0
  editor: 0
  editor_advanced_link: 0
  email_registration: 0
  email_registration_username: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_delete: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flexible_permissions: 0
  flood_control: 0
  front_page: 0
  gnode: 0
  google_analytics: 0
  group: 0
  help: 0
  history: 0
  hook_post_action: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  link: 0
  mailsystem: 0
  masquerade: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  mimemail: 0
  minifyhtml: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  queue_ui: 0
  r4032login: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  rest: 0
  search: 0
  sendgrid_integration: 0
  serialization: 0
  shortcut: 0
  statistics: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_import: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  workflows: 0
  xmlsitemap_custom: 0
  eca_form: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  claro: 0
  atom8_ui: 0
profile: minimal
