cloneable_entities:
  - backup_migrate_destination
  - backup_migrate_schedule
  - backup_migrate_source
  - backup_migrate_settings
  - block
  - captcha_point
  - field_config
  - field_storage_config
  - filter_format
  - node_type
  - node
  - path_alias
  - search_page
  - action
  - menu
  - user
  - user_role
  - date_format
  - entity_form_mode
  - entity_view_display
  - entity_form_display
  - entity_view_mode
  - base_field_override
  - xmlsitemap
  - block_content
  - block_content_type
  - file
  - editor
  - workflow
  - taxonomy_term
  - taxonomy_vocabulary
  - image_style
  - view
  - menu_link_content
  - rest_resource_config
  - crop
  - crop_type
  - webform
  - webform_submission
  - webform_options
  - metatag_defaults
  - paragraph
  - paragraphs_type
  - pathauto_pattern
  - redirect
  - content_moderation_state
  - eca
  - eca_model
  - comment_type
  - comment
  - shortcut_set
  - shortcut
  - paragraphs_library_item
  - profile_type
  - profile
  - entity_browser
  - group_relationship_type
  - group_config_wrapper
  - group
  - group_role
  - group_relationship
  - group_type
