enabled: false
disable_for_administrators: false
home_link_path: /dev-dashboard
roles:
  anonymous:
    enabled: null
    weight: 0
    path: ''
  authenticated:
    enabled: null
    weight: 0
    path: ''
  administrator:
    enabled: null
    weight: 0
    path: ''
