_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: e901d9a6-001f-4432-9055-57ade8ba8b90
name: 'Cash for Computer Scrap'
mail: rick@digitaldecibels.com
slogan: ''
page:
  403: /user/login
  404: ''
  front: /node/93
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
